### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Nikodem8378** [TiberiumFusion/Smd2Pac#2]
I have put smd file into the executable but it gave no txt file. Sorry my english sucks

**Comment by TiberiumFusion** [comment]
An error may have occurred. Run it from the command line to see the information output and any potential error messages. Post a screenshot of the output.

**Comment by Nikodem8378** [comment]
> An error may have occurred. Run it from the command line to see the information output and any potential error messages. Post a screenshot of the output.

Sorry I have saw this reply just now. I don't know how to run it from the command line. I'm new on github

**Comment by TiberiumFusion** [comment]
@Nikodem8378

No worries. Here's how to do that:

1. Open the folder where you extracted Smd2Pac
2. Copy your .smd files into that folder
3. **Hold Shift** and right-click in the folder, then choose _Open command window here_
4. Type out a command, then press enter to run it. Refer to the Examples section at the bottom of the [Wiki](https://github.com/TiberiumFusion/Smd2Pac/wiki) page.

For example, type out `Smd2Pac.exe taunt_muscle.smd` and press enter to run Smd2Pac on the file named `taunt_muscle.smd`. This is the same as dragging and dropping your .smd file onto Smd2Pac.exe.

The console window will show the program output, including any possible error messages or other helpful information. Please take a screenshot of the **full** console output and post it here.

![ExportToGif](https://github.com/user-attachments/assets/d9f9633a-d59e-4fb4-95e1-c8a47253ecfc)

**Comment by Nikodem8378** [comment]
![image](https://github.com/user-attachments/assets/055bbff0-7f04-423c-a56a-dbb843115f3d)
Here

**Comment by TiberiumFusion** [comment]
@Nikodem8378

Thanks.

Please share your SMD file. You can attach it to your message by clicking this:
![demo](https://github.com/user-attachments/assets/01d18ffa-bdb2-4bd1-b910-cd733849eda2)

The program is failing because your file does not match the expected SMD format. Smd2Pac only supports the standard SMD format used by Valve. Third-party Source games sometimes use custom SMD formats that are not compatible. It is also possible that your SMD is valid, but there may be a bug in Smd2Pac's SMD parser. So, I need the file you are using to further diagnose this issue.

**Comment by Nikodem8378** [comment]
Github does not support .smd files so I'm sending it to you in a not compressed ZIP file
[smd files.zip](https://github.com/user-attachments/files/16714540/smd.files.zip)
I actually wanted to convert these two files

**Comment by TiberiumFusion** [comment]
@Nikodem8378

Thanks for the files. I've identified the issue. In your SMD files, the bone names have spaces in them. Normally, bone names look like this: `ValveBiped.Bip01_Pelvis` (no spaces). But the strange bone names in your SMD file look like this `8wou01t0 l arm bone04`.

I've been under the belief that spaces are illegal in SMD bone names, but maybe that's not true. I'll change the SMD parser to accept spaces in bone names.

In the meantime, can you tell me where your SMD files came from? I see they were decompiled from an MDL by Crowbar. Which game were they decompiled from? Was it gmod? Was it an addon? Do you have a link to the model/addon so I can test it?

**Comment by Nikodem8378** [comment]
> @Nikodem8378
> 
> Thanks for the files. I've identified the issue. In your SMD files, the bone names have spaces in them. Normally, bone names look like this: `ValveBiped.Bip01_Pelvis` (no spaces). But the strange bone names in your SMD file look like this `8wou01t0 l arm bone04`.
> 
> I've been under the belief that spaces are illegal in SMD bone names, but maybe that's not true. I'll change the SMD parser to accept spaces in bone names.
> 
> In the meantime, can you tell me where your SMD files came from? I see they were decompiled from an MDL by Crowbar. Which game were they decompiled from? Was it gmod? Was it an addon? Do you have a link to the model/addon so I can test it?

I was making a Wonder of U PAC outfit and I needed animations from the game JoJo all star battle remastered and I couldn't extract the animations from this game so I borrowed it from this addon https://steamcommunity.com/sharedfiles/filedetails/?id=3240148502&searchtext= (I'm making this outfit just for me and I will not publish it anywhere)

**Comment by TiberiumFusion** [comment]
@Nikodem8378

Please try this version of Smd2Pac with your SMD files. Let me know if it solves the issue for you.
[Smd2Pac-1.2.2.0-rc1.zip](https://github.com/user-attachments/files/16715233/Smd2Pac-1.2.2.0-rc1.zip)

It now accepts the bone names in your SMD files and will give you a pac3 anim data output.

**Comment by Nikodem8378** [comment]
Thank you for solving my issue. It works
